name: review

on:
  push:

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-24.04

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI
        uses: dwmkerr/terminal-ai-action@v0.2.0
        with:
          command: |
            ai "what is a github action"
