name: review

on:
  push:

permissions:
  pull-requests: write

jobs:
    runs-on: ubuntu-24.04

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI
        uses: dwmkerr/terminal-ai-action
